//liên quan nhan_vien
export const STAFFS_LOADING = "STAFFS_LOADING";
export const STAFFS_FETCHING_FAILED = "STAFFS_FETCHING_FAILED";
export const STAFFS_DISPATCHING = "STAFFS_DISPATCHING";
export const ADD_STAFF="ADD_STAFF";

//liên quan phòng ban
export const DEPARTMENTS_LOADING = "DEPARTMENTS_LOADING";
export const DEPARTMENTS_FETCHING_FAILED = "DEPARTMENTS_FETCHING_FAILED";
export const DEPARTMENTS_DISPATCHING = "DEPARTMENTS_DISPATCHING";


//Liên quan thù lao nhân viên
export const STAFFSwage_LOADING = "STAFFSwage_LOADING";
export const STAFFSwage_FETCHING_FAILED = "STAFFSwage_FETCHING_FAILED";
export const STAFFSwage_DISPATCHING = "STAFFSwage_DISPATCHING";